using System.Text.Json;
using System.Text.Json.Serialization;
using RestaurantReservation.Services;

namespace RestaurantReservation;

public static class Program
{
    private static readonly int CustomerId = 1;
    private static readonly int ReservationId = 1;
    private static readonly int EmployeeId = 1;
    private static readonly int RestaurantId = 1;
    private static readonly int PartySize = 1;
    public static async Task Main(string[] args)
    {  
        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            ReferenceHandler = ReferenceHandler.IgnoreCycles 
        };
        
       Console.WriteLine("List of all Managers:");
       await EmployeeService.ListAllManagers(options);
       Console.WriteLine("------------------------------------");
       
       Console.WriteLine($"Get Reservations By CustomerId: {CustomerId}");
       await ReservationService.GetReservationsByCustomerId(CustomerId, options);
       Console.WriteLine("------------------------------------");
       
       Console.WriteLine($"Lists the orders placed on that specific reservation {ReservationId} along with the associated menu items.");
       await OrderService.ListOrdersAndMenuItems(ReservationId, options);
       Console.WriteLine("------------------------------------");
       
       Console.WriteLine($"Find the menu items ordered in that specific reservation {ReservationId} along with the associated menu items.");
       await MenuItemService.ListOrderedAndMenuItems(ReservationId, options);
       Console.WriteLine("------------------------------------");
       
       Console.WriteLine($"Calculates the average order amount for that specific employee {EmployeeId} along with the associated menu items.");
       await EmployeeService.CalculateAverageOrderAmount(EmployeeId, options);
       Console.WriteLine("------------------------------------");
       
       Console.WriteLine($"View that lists all the reservations with their associated customer and restaurant information");
       await ReservationService.GetReservationDetails();
       Console.WriteLine("------------------------------------");
       
       Console.WriteLine($"View that lists all employees with their respective restaurant details from a database view");
       await EmployeeService.ListEmployeesDetails(options);
       Console.WriteLine("------------------------------------");
       
       Console.WriteLine($"Calculate the total revenue generated by a specific restaurant {RestaurantId}");
       await RestaurantService.GetRestaurantRevenue(RestaurantId, options);
       Console.WriteLine("------------------------------------");
       
       Console.WriteLine($"Finding all customers who have made reservations with a party size greater than a certain value {PartySize}");
       await CustomerService.FindCustomersByPartySize(PartySize, options);
       Console.WriteLine("------------------------------------");
       
    }
}