using System.Text.Json;
using RestaurantReservation.Services;

namespace RestaurantReservation.Handlers;

public static class RestaurantHandler
{
    public static async Task GetRestaurantRevenue(int restaurantId, JsonSerializerOptions options)
    {
        Console.WriteLine($"Calculate the total revenue generated by a specific restaurant {restaurantId}");
        decimal? revenue = await RestaurantService.GetRestaurantRevenue(restaurantId);
        Console.WriteLine(JsonSerializer.Serialize(revenue, options));
        Console.WriteLine("------------------------------------");
    }
}